export const HELLO_PANEL = "HELLO_PANEL";
export const SELECT_TYPE_PANEL = "SELECT_TYPE_PANEL";

export const REGULAR_PANEL = "REGULAR_PANEL";
export const TARGET_PANEL = "TARGET_PANEL";
export const INVOICE_PANEL = "INVOICE_PANEL";
export const ADDITIONALLY_PANEL = "ADDITIONALLY_PANEL";

export const SNIPPET_PANEL = "SNIPPET_PANEL";
export const DEP_SNIPPET = "DEP_SNIPPET";
